### ISSUE TITLE
[SE(3)-Transformer] Output embeddings collapse 

### ISSUE THREAD

**Issue by anton-bushuiev** [NVIDIA/DeepLearningExamples#1341]
Related to **Model/Framework(s)** 
* *SE(3)-Transformer*

**Describe the bug**
I train SE(3)-Transformer to predict type-0 node embeddings. I notice that with multiple training hyper-parameter setups I get the same following error: after N epochs the model collapses to predict only full-NaN or sometimes full-0 features. Do you please have  any pointers what may be the issue?
```
# After some N training epochs in training loop:
h = self.se3transformer(data_dgl, node_feats, edge_feats, all_bases)
h = h['0'].squeeze(-1)
if torch.isnan(h).any():
    for i in range(h.shape[0]):
        print(f'h[{i}]', h[i, :])
```
<img width="920" alt="image" src="https://github.com/NVIDIA/DeepLearningExamples/assets/67932762/f42e2e6b-64f8-4d9e-b303-6bafac8267e0">

![Pasted Graphic 2](https://github.com/NVIDIA/DeepLearningExamples/assets/67932762/3e40fbcc-46d8-4003-8c8e-3d2014f0b810)

Complete hyper-parameter setup for the model in Hydra:
```
se3transformer:
    _target_: se3_transformer.model.SE3Transformer
    fiber_in:
      _target_: se3_transformer.model.fiber.Fiber
      _convert_: all
      structure:
        0: 20
        1: 1
    fiber_hidden:
      _target_: se3_transformer.model.fiber.Fiber.create
      num_degrees: 2
      num_channels: 32
    fiber_out:
      _target_: se3_transformer.model.fiber.Fiber
      _convert_: all
      structure:
        0: 512
    num_layers: 7
    num_heads: 8
    channels_div: 2
    norm: true
    use_layer_norm: true
```
I use default Adam with lr=1e-3 within PyToch Lightning. 

**Expected behavior**
No complete NaN or zero output type-0 features.

**Environment**
* Custom environment with Python 3.9.0 and torch==1.13.0+cu116
* GPUs in the system: 8x NVIDIA A100-SXM4-40GB
* CUDA driver version: 535.54.03 (CUDA Version: 12.2)
